Repository 9oormthon-univ/2024_DANPOONG_TEAM_38_BE, pull requests merged in 2024-11, with the labels that each got.

#4 [FEAT] Docker 환경 설정 추가
  docker-compose.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: feat

#8 [FEAT] web, swagger, redis 관련 설정 파일 추가
  build.gradle
  src/main/java/boosters/fundboost/global/config/RedisConfig.java
  src/main/java/boosters/fundboost/global/config/SwaggerConfig.java
  src/main/java/boosters/fundboost/global/config/WebConfig.java
  src/main/java/boosters/fundboost/global/redis/RefreshToken.java
  src/main/java/boosters/fundboost/global/redis/repository/RefreshTokenRepository.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: feat

#7 [FEAT] API 응답 통일 및 예외 처리 코드 작성
  build.gradle
  src/main/java/boosters/fundboost/global/response/BaseResponse.java
  src/main/java/boosters/fundboost/global/response/code/BaseCode.java
  src/main/java/boosters/fundboost/global/response/code/BaseErrorCode.java
  src/main/java/boosters/fundboost/global/response/code/ErrorReasonDTO.java
  src/main/java/boosters/fundboost/global/response/code/ReasonDTO.java
  src/main/java/boosters/fundboost/global/response/code/status/ErrorStatus.java
  src/main/java/boosters/fundboost/global/response/code/status/SuccessStatus.java
  src/main/java/boosters/fundboost/global/response/exception/ExceptionAdvice.java
  src/main/java/boosters/fundboost/global/response/exception/GeneralException.java
Labels: feat

#11 [FEAT] 시큐리티 설정
  build.gradle
  src/main/java/boosters/fundboost/global/redis/exception/TokenException.java
  src/main/java/boosters/fundboost/global/response/code/status/ErrorStatus.java
  src/main/java/boosters/fundboost/global/security/config/SecurityConfig.java
  src/main/java/boosters/fundboost/global/security/jwt/JwtTokenFilter.java
  src/main/java/boosters/fundboost/global/security/jwt/JwtTokenProvider.java
  src/main/java/boosters/fundboost/global/security/refreshToken/RefreshTokenRequest.java
  src/main/java/boosters/fundboost/global/security/refreshToken/RefreshTokenResponse.java
  src/main/java/boosters/fundboost/global/security/userdetails/CustomUserDetails.java
  src/main/java/boosters/fundboost/global/security/userdetails/CustomUserDetailsService.java
  src/main/java/boosters/fundboost/user/repository/UserRepository.java
Labels: feat

#14 [FEAT] 카카오 로그인, 로그아웃, 리프레시 토큰 재발급 API구현
  src/main/java/boosters/fundboost/global/config/WebConfig.java
  src/main/java/boosters/fundboost/global/redis/service/RefreshTokenService.java
  src/main/java/boosters/fundboost/global/response/BaseResponse.java
  src/main/java/boosters/fundboost/global/response/code/status/ErrorStatus.java
  src/main/java/boosters/fundboost/global/security/handler/annotation/AuthToken.java
  src/main/java/boosters/fundboost/global/security/handler/annotation/AuthUser.java
  src/main/java/boosters/fundboost/global/security/handler/resolver/AuthUserArgumentResolver.java
  src/main/java/boosters/fundboost/global/security/handler/resolver/TokenArgumentResolver.java
  src/main/java/boosters/fundboost/global/security/provider/KakaoAuthProvider.java
  src/main/java/boosters/fundboost/user/auth/controller/AuthController.java
  src/main/java/boosters/fundboost/user/auth/converter/AuthConverter.java
  src/main/java/boosters/fundboost/user/auth/dto/AuthResponse.java
  src/main/java/boosters/fundboost/user/auth/dto/KakaoProfile.java
  src/main/java/boosters/fundboost/user/auth/exception/AuthException.java
  src/main/java/boosters/fundboost/user/auth/service/AuthService.java
  src/main/java/boosters/fundboost/user/auth/service/impl/AuthServiceImpl.java
  src/main/java/boosters/fundboost/user/exception/UserException.java
  src/main/java/boosters/fundboost/user/service/UserService.java
  src/main/java/boosters/fundboost/user/service/UserServiceImpl.java
Labels: feat, refactor

#23 [FEAT] 신규 등록된 3가지 프로젝트 조회 기능 구현
  src/main/java/boosters/fundboost/global/utils/CalculatorUtil.java
  src/main/java/boosters/fundboost/global/utils/PeriodUtil.java
  src/main/java/boosters/fundboost/project/controller/ProjectController.java
  src/main/java/boosters/fundboost/project/converter/ProjectConverter.java
  src/main/java/boosters/fundboost/project/domain/Project.java
  src/main/java/boosters/fundboost/project/domain/enums/Progress.java
  src/main/java/boosters/fundboost/project/domain/enums/ProjectCategory.java
  src/main/java/boosters/fundboost/project/domain/enums/Region.java
  src/main/java/boosters/fundboost/project/dto/response/NewProjectResponse.java
  src/main/java/boosters/fundboost/project/repository/ProjectRepository.java
  src/main/java/boosters/fundboost/project/service/ProjectService.java
  src/main/java/boosters/fundboost/project/service/ProjectServiceImpl.java
Labels: feat

#24 [FEAT] 프로젝트 정보 등록
  build.gradle
  dump.rdb
  src/main/java/boosters/fundboost/global/config/S3Config.java
  src/main/java/boosters/fundboost/global/security/userdetails/CustomUserDetails.java
  src/main/java/boosters/fundboost/global/security/util/SecurityUtils.java
  src/main/java/boosters/fundboost/global/uploader/S3Uploader.java
  src/main/java/boosters/fundboost/project/controller/ProjectController.java
  src/main/java/boosters/fundboost/project/converter/ProjectConverter.java
  src/main/java/boosters/fundboost/project/domain/Project.java
  src/main/java/boosters/fundboost/project/domain/enums/Progress.java
  src/main/java/boosters/fundboost/project/domain/enums/Region.java
  src/main/java/boosters/fundboost/project/dto/request/ProjectBasicInfoRequest.java
  src/main/java/boosters/fundboost/project/repository/ProjectRepository.java
  src/main/java/boosters/fundboost/project/service/ProjectService.java
  src/main/java/boosters/fundboost/project/service/ProjectServiceImpl.java
  src/main/resources/application.yml
Labels: feat

#26 [FEAT] 프로젝트 등록 시작일 마감일 설정
  dump.rdb
  src/main/java/boosters/fundboost/project/converter/ProjectConverter.java
  src/main/java/boosters/fundboost/project/dto/request/ProjectBasicInfoRequest.java
Labels: feat

#29 [FEAT] 메인페이지의 정렬 기준에 따른 랭킹 조회 기능 구현
  .gitignore
  build.gradle
  src/main/java/boosters/fundboost/boost/domain/Boost.java
  src/main/java/boosters/fundboost/company/controller/CompanyController.java
  src/main/java/boosters/fundboost/company/converter/CompanyRankingConverter.java
  src/main/java/boosters/fundboost/company/domain/Company.java
  src/main/java/boosters/fundboost/company/domain/enums/CompanyCategory.java
  src/main/java/boosters/fundboost/company/dto/CompanyRankingRecord.java
  src/main/java/boosters/fundboost/company/dto/request/CompanyRankingRequest.java
  src/main/java/boosters/fundboost/company/dto/response/CompanyRankingResponse.java
  src/main/java/boosters/fundboost/company/repository/CompanyRepository.java
  src/main/java/boosters/fundboost/company/repository/CustomCompanyRepository.java
  src/main/java/boosters/fundboost/company/repository/CustomCompanyRepositoryImpl.java
  src/main/java/boosters/fundboost/company/service/CompanyService.java
  src/main/java/boosters/fundboost/global/common/domain/enums/SortType.java
  src/main/java/boosters/fundboost/global/config/QuerydslConfig.java
  src/main/java/boosters/fundboost/global/exception/ValidationException.java
  src/main/java/boosters/fundboost/project/domain/Project.java
Labels: feat

#30 [FEAT] 프로젝트 상세조회
  dump.rdb
  src/main/java/boosters/fundboost/global/response/code/status/ErrorStatus.java
  src/main/java/boosters/fundboost/project/controller/ProjectController.java
  src/main/java/boosters/fundboost/project/converter/ProjectConverter.java
  src/main/java/boosters/fundboost/project/dto/response/ProjectDetailResponse.java
  src/main/java/boosters/fundboost/project/exception/ProjectException.java
  src/main/java/boosters/fundboost/project/service/ProjectService.java
  src/main/java/boosters/fundboost/project/service/ProjectServiceImpl.java
  src/main/resources/application.yml
Labels: feat

#44 [FEAT] 후원한 프로젝트 조회 기능 구현 및 boost와 user 연관관계 추가
  src/main/java/boosters/fundboost/boost/domain/Boost.java
  src/main/java/boosters/fundboost/boost/repository/BoostRepository.java
  src/main/java/boosters/fundboost/boost/service/BoostService.java
  src/main/java/boosters/fundboost/boost/service/BoostServiceImpl.java
  src/main/java/boosters/fundboost/company/domain/Company.java
  src/main/java/boosters/fundboost/company/repository/CustomCompanyRepositoryImpl.java
  src/main/java/boosters/fundboost/project/converter/ProjectConverter.java
  src/main/java/boosters/fundboost/project/service/ProjectServiceImpl.java
  src/main/java/boosters/fundboost/user/controller/UserController.java
  src/main/java/boosters/fundboost/user/domain/User.java
  src/main/java/boosters/fundboost/user/service/UserService.java
  src/main/java/boosters/fundboost/user/service/UserServiceImpl.java
Labels: feat, refactor

#46 [FEAT] 프로젝트의 후원정보를 조회하는 기능 구현
  src/main/java/boosters/fundboost/boost/converter/BoostedInfoConverter.java
  src/main/java/boosters/fundboost/boost/dto/BoostedInfoResponse.java
  src/main/java/boosters/fundboost/boost/repository/BoostRepository.java
  src/main/java/boosters/fundboost/global/utils/AmountUtil.java
  src/main/java/boosters/fundboost/project/controller/ProjectController.java
  src/main/java/boosters/fundboost/project/service/ProjectService.java
  src/main/java/boosters/fundboost/project/service/ProjectServiceImpl.java
Labels: feat

#48 [FEAT] 프로젝트 후원 기능 구현
  src/main/java/boosters/fundboost/boost/controller/BoostController.java
  src/main/java/boosters/fundboost/boost/domain/Boost.java
  src/main/java/boosters/fundboost/boost/service/BoostService.java
  src/main/java/boosters/fundboost/boost/service/BoostServiceImpl.java
  src/main/java/boosters/fundboost/project/dto/request/BoostProjectRequest.java
  src/main/java/boosters/fundboost/project/service/ProjectService.java
  src/main/java/boosters/fundboost/project/service/ProjectServiceImpl.java
  src/main/resources/application-dev.yml
Labels: feat

#50 [FEAT] 후기 등록
  dump.rdb
  src/main/java/boosters/fundboost/boost/domain/Boost.java
  src/main/java/boosters/fundboost/boost/reopsitory/BoostRepository.java
  src/main/java/boosters/fundboost/global/response/code/status/ErrorStatus.java
  src/main/java/boosters/fundboost/project/domain/Project.java
  src/main/java/boosters/fundboost/review/controller/ReviewController.java
  src/main/java/boosters/fundboost/review/converter/ReviewConverter.java
  src/main/java/boosters/fundboost/review/domain/Review.java
  src/main/java/boosters/fundboost/review/domain/enums/ReviewType.java
  src/main/java/boosters/fundboost/review/dto/request/ReviewRequestDto.java
  src/main/java/boosters/fundboost/review/dto/response/ReviewResponseDto.java
  src/main/java/boosters/fundboost/review/exception/ReviewException.java
  src/main/java/boosters/fundboost/review/repository/ReviewRepository.java
  src/main/java/boosters/fundboost/review/service/ReviewService.java
  src/main/java/boosters/fundboost/review/service/ReviewServiceImpl.java
  src/main/java/boosters/fundboost/user/service/UserService.java
  src/main/java/boosters/fundboost/user/service/UserServiceImpl.java
Labels: feat

#53 [BUG] 중복 파일 삭제
  dump.rdb
  src/main/java/boosters/fundboost/boost/domain/Boost.java
  src/main/java/boosters/fundboost/boost/reopsitory/BoostRepository.java
  src/main/java/boosters/fundboost/boost/repository/BoostRepository.java
  src/main/java/boosters/fundboost/review/service/ReviewServiceImpl.java
  src/main/resources/application-dev.yml
Labels: bug

#56 [FIX] Principle 등록시 설정한 유저 이메일로 정보 찾아오도록 수정 및 유저, 기업 태그 기본 값 설정
  src/main/java/boosters/fundboost/company/service/CompanyService.java
  src/main/java/boosters/fundboost/global/security/handler/resolver/AuthUserArgumentResolver.java
  src/main/java/boosters/fundboost/user/domain/User.java
  src/main/java/boosters/fundboost/user/service/UserService.java
  src/main/java/boosters/fundboost/user/service/UserServiceImpl.java
Labels: !HOTFIX

#58 [FEAT] 팔로우, 언팔로우 기능 구현 및 익명 유저 로그인 요청 시 적절한 예외응답으로 수정
  src/main/java/boosters/fundboost/follow/controller/FollowController.java
  src/main/java/boosters/fundboost/follow/domain/Follow.java
  src/main/java/boosters/fundboost/follow/exception/FollowException.java
  src/main/java/boosters/fundboost/follow/repository/FollowRepository.java
  src/main/java/boosters/fundboost/follow/service/FollowService.java
  src/main/java/boosters/fundboost/follow/service/FollowServiceImpl.java
  src/main/java/boosters/fundboost/global/response/code/status/ErrorStatus.java
  src/main/java/boosters/fundboost/global/security/handler/resolver/AuthUserArgumentResolver.java
  src/main/java/boosters/fundboost/global/utils/UserValidator.java
Labels: feat, refactor

#65 [FEAT] 프로필 편집 기능 구현
  src/main/java/boosters/fundboost/global/controller/UserCompanyController.java
  src/main/java/boosters/fundboost/global/uploader/S3UploaderService.java
  src/main/java/boosters/fundboost/user/domain/User.java
  src/main/java/boosters/fundboost/user/dto/request/ProfileEditRequest.java
  src/main/java/boosters/fundboost/user/service/UserService.java
  src/main/java/boosters/fundboost/user/service/UserServiceImpl.java
Labels: feat

#66 [FEAT] 제안서 작성 기능 구현 및 프로필 편집시 입력 받는 이미지 유효성 검증 추가
  src/main/java/boosters/fundboost/company/domain/Company.java
  src/main/java/boosters/fundboost/company/exception/CompanyException.java
  src/main/java/boosters/fundboost/company/service/CompanyService.java
  src/main/java/boosters/fundboost/global/common/domain/enums/UploadType.java
  src/main/java/boosters/fundboost/global/exception/S3Exception.java
  src/main/java/boosters/fundboost/global/response/code/status/ErrorStatus.java
  src/main/java/boosters/fundboost/global/uploader/S3UploaderService.java
  src/main/java/boosters/fundboost/global/utils/FileValidator.java
  src/main/java/boosters/fundboost/proposal/controller/ProposalController.java
  src/main/java/boosters/fundboost/proposal/domain/Proposal.java
  src/main/java/boosters/fundboost/proposal/repository/ProposalRepository.java
  src/main/java/boosters/fundboost/proposal/service/ProposalService.java
  src/main/java/boosters/fundboost/proposal/service/ProposalServiceImpl.java
  src/main/java/boosters/fundboost/user/dto/request/ProfileEditRequest.java
  src/main/java/boosters/fundboost/user/dto/request/ProposalRequest.java
  src/main/java/boosters/fundboost/user/service/UserServiceImpl.java
Labels: feat, refactor

#68 [FEAT] 프로젝트 조회-기업 후원 상태 추가
  src/main/java/boosters/fundboost/project/converter/ProjectConverter.java
  src/main/java/boosters/fundboost/project/dto/response/NewProjectResponse.java
  src/main/java/boosters/fundboost/project/repository/ProjectRepository.java
Labels: feat

#70 [FEAT] 프로젝트 등록 - 요약추가
  dump.rdb
  src/main/java/boosters/fundboost/project/converter/ProjectConverter.java
  src/main/java/boosters/fundboost/project/domain/Project.java
  src/main/java/boosters/fundboost/project/dto/request/ProjectBasicInfoRequest.java
  src/main/java/boosters/fundboost/project/dto/response/ProjectDetailResponse.java
Labels: feat

#71 [FEAT] 프로젝트 검색 기능 구현
  src/main/java/boosters/fundboost/global/exception/SearchException.java
  src/main/java/boosters/fundboost/global/response/code/status/ErrorStatus.java
  src/main/java/boosters/fundboost/global/utils/SearchValidator.java
  src/main/java/boosters/fundboost/project/controller/ProjectController.java
  src/main/java/boosters/fundboost/project/converter/ProjectConverter.java
  src/main/java/boosters/fundboost/project/dto/response/ProjectPreviewResponse.java
  src/main/java/boosters/fundboost/project/repository/CustomProjectRepository.java
  src/main/java/boosters/fundboost/project/repository/CustomProjectRepositoryImpl.java
  src/main/java/boosters/fundboost/project/service/ProjectService.java
  src/main/java/boosters/fundboost/project/service/ProjectServiceImpl.java
Labels: feat

#73 [FEAT] 프로젝트 좋아요
  dump.rdb
  src/main/java/boosters/fundboost/like/controller/LikeController.java
  src/main/java/boosters/fundboost/like/domain/Like.java
  src/main/java/boosters/fundboost/like/dto/LikeCountResponse.java
  src/main/java/boosters/fundboost/like/exception/LikeException.java
  src/main/java/boosters/fundboost/like/repository/LikeRepository.java
  src/main/java/boosters/fundboost/like/service/LikeService.java
  src/main/java/boosters/fundboost/like/service/LikeServiceImpl.java
Labels: feat

#78 [feat] 유저 회원가입시 정보 디폴트값 설정 및 불필요 칼럼 삭제
  src/main/java/boosters/fundboost/boost/domain/Boost.java
  src/main/java/boosters/fundboost/global/utils/NameUtil.java
  src/main/java/boosters/fundboost/user/auth/converter/AuthConverter.java
Labels: feat, !HOTFIX

#84 [FIX] "/api/project/all" 페이징처리 방법 수정
  dump.rdb
  src/main/java/boosters/fundboost/project/controller/ProjectController.java
  src/main/java/boosters/fundboost/project/dto/request/NewProjectRequest.java
  src/main/java/boosters/fundboost/project/repository/ProjectRepository.java
Labels: FIX

#87 [FIX] 제안서 미리보기 조회시 id값 같이 응답하도록 수정
  src/main/java/boosters/fundboost/proposal/converter/ProposalConverter.java
  src/main/java/boosters/fundboost/proposal/dto/response/ProposalPreviewResponse.java
Labels: FIX

#90 [FIX] 프로젝트 이미지 다중 업로드
  dump.rdb
  src/main/java/boosters/fundboost/global/uploader/S3Uploader.java
  src/main/java/boosters/fundboost/project/controller/ProjectController.java
  src/main/java/boosters/fundboost/project/converter/ProjectConverter.java
  src/main/java/boosters/fundboost/project/domain/Project.java
  src/main/java/boosters/fundboost/project/domain/ProjectImage.java
  src/main/java/boosters/fundboost/project/dto/request/ProjectBasicInfoRequest.java
  src/main/java/boosters/fundboost/project/dto/response/ProjectDetailResponse.java
  src/main/java/boosters/fundboost/project/service/ProjectService.java
  src/main/java/boosters/fundboost/project/service/ProjectServiceImpl.java
Labels: feat, FIX

#93 [FIX] 나의 프로젝트 조회 수정
  dump.rdb
  src/main/java/boosters/fundboost/project/controller/ProjectController.java
  src/main/java/boosters/fundboost/project/converter/ProjectConverter.java
  src/main/java/boosters/fundboost/project/dto/response/MyProjectResponse.java
  src/main/java/boosters/fundboost/project/service/ProjectService.java
  src/main/java/boosters/fundboost/project/service/ProjectServiceImpl.java
Labels: feat, FIX

#96 [FIX] 기업 사용자 후원 시 프로젝트 상태 변경
  dump.rdb
  src/main/java/boosters/fundboost/boost/controller/BoostController.java
  src/main/java/boosters/fundboost/project/domain/Project.java
  src/main/java/boosters/fundboost/project/service/ProjectService.java
  src/main/java/boosters/fundboost/project/service/ProjectServiceImpl.java
Labels: feat, FIX

#102 [FIX] 내가 작성한 리뷰 에러처리
  src/main/java/boosters/fundboost/global/config/WebConfig.java
  src/main/java/boosters/fundboost/review/service/ReviewServiceImpl.java
Labels: FIX

#105 [FEAT] 상대가 후원한 프로젝트 조회 API 작성
  src/main/java/boosters/fundboost/boost/controller/BoostController.java
Labels: feat

#115 [REFACTOR] 파일확장자 검증 임시 수정 및 컨버터 유틸리티 클래스로 수정
  src/main/java/boosters/fundboost/company/service/CompanyService.java
  src/main/java/boosters/fundboost/global/response/code/status/ErrorStatus.java
  src/main/java/boosters/fundboost/global/security/util/SecurityUtils.java
  src/main/java/boosters/fundboost/global/uploader/S3UploaderService.java
  src/main/java/boosters/fundboost/project/controller/ProjectController.java
  src/main/java/boosters/fundboost/project/converter/ProjectConverter.java
  src/main/java/boosters/fundboost/project/service/ProjectServiceImpl.java
Labels: refactor

#121 [REFACTOR] 내 후기 조회에 필요한 유저 아이디 정보를 마이페이지 조회시 전달
  src/main/java/boosters/fundboost/user/converter/MyPageConverter.java
  src/main/java/boosters/fundboost/user/dto/response/UserMyPageResponse.java
Labels: FIX

#127 [FIX] 토큰 저장 방법 통일 및 리프레시 토큰 문제 해결
  src/main/java/boosters/fundboost/global/redis/RefreshToken.java
  src/main/java/boosters/fundboost/global/redis/repository/RefreshTokenRepository.java
  src/main/java/boosters/fundboost/global/redis/service/RefreshTokenService.java
  src/main/java/boosters/fundboost/global/security/handler/resolver/TokenArgumentResolver.java
  src/main/java/boosters/fundboost/global/security/jwt/JwtTokenProvider.java
  src/main/java/boosters/fundboost/user/auth/controller/AuthController.java
  src/main/java/boosters/fundboost/user/auth/service/AuthService.java
  src/main/java/boosters/fundboost/user/auth/service/impl/AuthServiceImpl.java
Labels: FIX

#130 [REFACTOR] 3개 조회 리밋 제거해 전체 조회되도록 수정
  src/main/java/boosters/fundboost/company/repository/CustomCompanyRepositoryImpl.java
Labels: refactor
